#!/bin/bash

PROJECT=example

function run() {
  XSOCK=/tmp/.X11-unix
  XAUTH=/tmp/.docker.xauth
  touch $XAUTH
  xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

  docker run -it -d --rm \
          --name=$PROJECT \
          --volume=$XSOCK:$XSOCK:rw \
          --volume=$XAUTH:$XAUTH:rw \
          --env="XAUTHORITY=${XAUTH}" \
          --env="DISPLAY" \
          --volume=$HOME/.config/nvim:/home/ubuntu/.config/nvim:ro \
          --volume=$HOME/.local/share/nvim/lazy:/home/ubuntu/.local/share/nvim/lazy:rw \
          --volume=$HOME/.gitconfig:/home/ubuntu/.gitconfig:ro \
          --volume=$HOME/.ssh:/home/ubuntu/.ssh:ro \
          --volume=./:/home/ubuntu/mnt:rw \
      prj:$PROJECT

  docker inspect -f "{{ .NetworkSettings.IPAddress }}" $PROJECT

  docker attach $PROJECT
}

function conn() {
  docker exec -it $PROJECT /bin/bash
}

function build() {
  docker build -t prj:$PROJECT .
}

function clean() {
  rm -rf _build _install
}

case ${1} in
    run ) run;;
    conn ) conn;;
    build ) build;;
    clean ) clean;;
esac
